### ISSUE TITLE
Featured image looks not well when is in archive

### ISSUE THREAD

**Issue by PaulStogov** [nithou/tiny-blog-engine#6]
Hello there! Thanks for a wonderful blog engine!
Found some minor unpleasant thing. I added a featured image post according to [wiki](https://github.com/nithou/tiny-blog-engine/wiki#adding-a-featured-image) and it looks like that in archive page the image is not parsed well.

![image](https://github.com/user-attachments/assets/fdf7a987-3958-458d-a360-fe57d804371b)
![image](https://github.com/user-attachments/assets/6150b6b1-226a-4801-ac95-6ee739e5afe0)

**Comment by nithou** [comment]
Oh thanks for spotting! I think I get where this is coming from and linked to the rework I'm working on! I should push an update in the coming days!

https://github.com/nithou/tiny-blog-engine/issues/7

**Comment by nithou** [comment]
Should be solved through the last update, can you check if it works on your side?
(You will need to add a title property to posts & pages to ensure it works)

**Comment by PaulStogov** [comment]
It works like a charm now. Thank you very much!
